### PR TITLE
StudentQuiz: Behat tests could be improved

### PR DESCRIPTION
**Pull request by nguyenphuctien**
The summary of my working:

1. I tried to remove as much as possible the @javascript tag
2. I tried to correct the 'Give' 'When' 'Then' statement in each scenario
3. I defined the step: I am on the "]StudentQuizName]" "mod_studentquiz > [Pagetype]" page for student quiz
4. I have fixed the deprecated function get_all_user_name_fields() 
5. I tried to remove duplicated code to move them to the Background if it is possible
6. The step "I add a "activity" to section "sectionnumber" and I fill the form with:" has been changed recently. It need @javascript tag to run.

In the near future, I will continue to improve the behat tests for comments. There are many "waiting" step that shouldn't include into the test case, but the js implement is not working correctly (The js_pending isn't used in all case that it should be).

### CODE REVIEW

**Comment by dionysius** [comment]
Hey, sorry for taking a while. I've merged this into https://github.com/frankkoch/moodle-mod_studentquiz/tree/nguyenphuctien-wip449578 which would be ready to merge into master but the following behat error got introduced with this PR:

```
001 Scenario: Admin and user can sortable.                                                # /home/travis/build/moodle/mod/studentquiz/tests/behat/comment_area_create.feature:279
      And I should not see "Forename" in the ".studentquiz-comment-filters" "css_element" # /home/travis/build/moodle/mod/studentquiz/tests/behat/comment_area_create.feature:392
        "Forename" text was found in the ".studentquiz-comment-filters" element
```

[previously on travis](https://travis-ci.org/github/frankkoch/moodle-mod_studentquiz/jobs/772560362#L1272), reproducable on my local environment, and will probably be visible with the in the currently running [github actions for this pushed branch](https://github.com/frankkoch/moodle-mod_studentquiz/actions/runs/1019003852)

**Comment by timhunt** [comment]
Hi @nguyenphuctien, would you be able to rebase this on the latest master branch? Would be good to get this merged. Thanks.

**Comment by nguyenphuctien** [comment]
Hi @timhunt,

Sorry for missing it for along time.

I have updated the code and resolve all conflicts. The git action is not stable. I re-run many times and sometimes the job passed, sometime the job failed. It also happen with the master branch.

Best wishes,

**Comment by dionysius** [comment]
Meta: I've approved that this PR is allowed to run in Actions (it was a button from github for PRs of "newly" contributers)

**Comment by timhunt** [comment]
Note, that Behat fail is spurious. See Issue #323.

**Pull request merged**
