### PR TITLE
Studentquiz: Add "Reviewable" state

### PR DESCRIPTION
**Pull request by JBThong**
Hi Tim, I have created the PR for adding a new state "Reviewable"

I have some notes for this commit:

1. On the filter area, add the new state "Reviewable" after the "Changed" state so that the user can choose this state to filter the question list
image

2. On the question list, add a new icon to identify the “Reviewable” state on the S column
image

3.  On the state dropdown list for review page/ Start attempt/ confirm pop up for Tutor/ Admin role
image

4. On preview page for own Student question with student role.

- Update the dropdown list so that the student can update to "Changed", "Reviewable", or "Delete" own question. 
image

- The student can not delete their own question when the question is in the state "Approved". Display error message: "You cannot delete an approved question" when deleting own question have state "Approved"
image

5. Push notification to Tutor/ admin role when students mark new “Reviewable” question and it works with the digest settings.

The template email follows the template below.

**Single email:**
Dear [Teacher name],
  
[Course shortname] StudentQuiz activity (["**name**"]): question "[**question name**]" was set to "[**State**]" by [**Studentname**],[**Date**], [**Time**].
image

**Digest email:**
  Dear Anonymous Manager,
  This is your daily digest of notifications for the StudentQuiz activity [**name**], available here: [URL].

  ...

  The question "[**question name**]" was set to "Reviewable" by [**Student name**]. 
dialy digest

Could you please help me review it after you back to work, @timhunt?
 Have a great vacation, Tim.

### CODE REVIEW

**Comment by JBThong** [comment]
So sorry about missing update new text in the behat step, I have updated it.

Thanks,

**Review by timhunt — CHANGES_REQUESTED** [review]
I'm sorry. My review got interrupted last night, before I had finished reviewing. I have finished now.

Overall, this is a lot of very good work. Just a few thing that should be fixed before this can be merged.

**Comment by timhunt** [comment]
The automated test failures seem to be caused by a new rule in local_codechecker. That is not related to these changes, so, I think we should fix that in a separate issue. I will make one.

**Comment by JBThong** [comment]
Thanks for your feedback, Tim

I have updated my code in this [commit](https://github.com/JBThong/moodle-mod_studentquiz/commit/23dcff3a3f7e148a4871e4ebf18dd9efad54d745). I have rebased the commit too. Could you please help me to review it again?

Thanks,

**Comment by timhunt** [comment]
Thanks for providing the changes as a separate commit Thong. That saves me lots of time, and almost all the changes are spot on except:

You cannot write

```php
$canmanage = !has_capability('mod/studentquiz:manage', $context);
```

(unless you are trying to enter something like https://www.ioccc.org/ ;-)) Please can you remove the ! from that line, add it back where needed, so the variable does what its name suggests. Thanks.

**Comment by JBThong** [comment]
Yes, many thanks, Tim.

I have updated my changes in this [commit](https://github.com/JBThong/moodle-mod_studentquiz/commit/f6c33e91fbc0078fa0afa6dd68c2292b35e73844). Could you please help me review it again?

Thanks

**Comment by timhunt** [comment]
There was one other mention of $canmange, which also needs to be updated! (line 108)

**Comment by JBThong** [comment]
So sorry about this, Tim. I have a big mistake. I think I should be slow to be more careful. I have updated it again.

Could you please help me review it again? 
Many thanks

**Comment by timhunt** [comment]
Thanks Thong. I have merged this now.

**Pull request merged**
